name: "example-cron-action"
on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Testando qualquer coisa
        run: echo "Funcionou"
