name: "example-cron-action"
on:
  schedule:
    - cron:  '*/2 * * * *'    # At every 15th minute

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Testando qualquer coisa
        run: echo "Funcionou"
