name: "example-cron-action"
on:
  push:
  

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Testando qualquer coisa
        run: echo "Funcionou"
